# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:
  static:
  media:

services:
  db:
    restart: always
    image: postgres:13.10
    env_file: .env
    container_name: db
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    restart: always
    image: rolicat/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: rolicat/foodgram_frontend:latest
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  gateway:
    restart: always
    image: rolicat/foodgram_gateway:latest
    volumes:
      - static:/staticfiles/
      - media:/media/
    depends_on:
      - backend
    ports:
      - 8000:80
